mod a1;
mod a2;
mod a3a;
mod a3b;
mod a4a;
mod a4b;
mod a5;
mod cwt_match;
mod a6;
mod a7;
mod a8;
mod a9;
mod Access;
mod a10;
mod a11;
mod Move;
mod a12;
mod a13Demo;
mod a13;
mod a14;
mod a15;
mod a15v2;
mod MenuChoice;
mod a16;
mod a17;
mod a18;
mod a18b;
mod a19;

fn main() {
    println!("Running scripts...");

    a1::main();
    println!("a1 pass");
    a2::main();
    println!("a2 pass");
    a3a::main();
    println!("a3a pass");
    a3b::main();
    println!("a3b pass");
    a4a::main();
    println!("a4a pass");
    a4b::main();
    println!("a4b pass");
    a5::main();
    println!("a5 pass");
    cwt_match::main();
    println!("cwt pass");
    a6::main();
    println!("a6 pass");
    a7::main();
    println!("a7 pass");
    a8::main();
    println!("a8 pass");
    a9::main();
    println!("a9 pass");
    Access::main();
    println!("access pass");
    a10::main();
    println!("a10 pass");
    a11::main();
    println!("a11 pass");
    Move::main();
    println!("Move pass");
    a12::main();
    println!("a12 pass");
    a13Demo::main();
    println!("a13Demo pass");
    a13::main();
    println!("a13 pass");
    a14::main();
    println!("a14 pass");
    a15::main();
    println!("a15 pass");
    a15v2::main();
    println!("a15 v2 pass");
    //MenuChoice::main();
    //println!("MenuChoice pass");
    a16::main();
    println!("a16 pass");
    a17::main();
    println!("a17 pass");
    a18::main();
    println!("a18 pass");
    a18b::main();
    println!("a18b pass");
    a19::main();
    println!("a19 pass");
    println!("Scripts completed");

}